config/routes.rb
Rails.application.routes.draw do
  
  get 'users/show'

  devise_for :users
  
  resources :classrooms,  
            :events,  
            :subscriptions,  
            :questions,  
            :topics,  
            :answers,
            :notifications
  
  get '/users/:id/show', to: 'users#show', as: 'user'
  
  get '/classroom/apply', to: 'classrooms#new_registration'
  
  post '/classroom/register', to: 'classrooms#register', as: 'registry'
  
  get '/users/:id/show', to: 'users#show', as: 'user_path'
  post '/questions/new'
  post '/answers/new'
  
  root 'welcome#index'

  get 'questions/rank_up'
  post 'questions/rank_up'
  get 'questions/rank_down'
  post 'questions/rank_down'
  post 'questions/_show'

end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :topic
  has_many :answers
  has_many :subscriptions

  def self.open
    0
  end

  def self.author_approved
    1
  end

  def self.instructor_approved
    2
  end

  def self.both_approved
    3
  end

  def self.instructor_flagged
    4
  end

  def find_author
    return self.subscriptions.find_by(status: Subscription.author).user 
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:show, :edit, :update, :destroy]
  
  def index
    topic_id = params[:topic_id]
    @questions = Question.where(topic_id: topic_id).order(rank: :desc)
  end

  def new
    @question = Question.new
    @topic = Topic.find(flash[:topic_id])
    flash[:topic_id] = @topic.id
  end

  def create
    respond_to do |format|
      @question = Question.new(question_params)
      if @question.save
        @question.update(topic_id: flash[:topic_id], status: Question.open, rank: 0) 
        Subscription.create(status: Subscription.author, question_id: @question.id, user_id: current_user.id)
        format.html { redirect_to @question.topic, notice: "Pergunta feita com sucesso." }
      else
        format.html { render 'new' }
      end
    end
  end

  def edit
    @user = question.find_author
    if current_user.id != @user.id
      redirect_to @question
    end
  end

  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html {redirect_to @question, notice: "Pergunta atualizada com sucesso."}
      else
        format.html {redirect_to :edit}
      end
    end
  end

  def destroy
    # Clean up dependent tables
    @question.answers.each do |answer|
      answer.destroy
    end
    
    @question.subscriptions.each do |subscription|
      subscription.destroy
    end
    # All cleaned up, now destroy the question
    @question.destroy

    respond_to do |format|
      format.html { redirect_to questionss_url, notice: "Pergunta removida com sucesso"}
    end
  end

  def show
    @answers = @question.answers.order(rank: :desc)
    flash[:question_id] = @question.id
  end
 
  def rank_up
    @question = Question.find(params[:question_id])
    case current_user.id
    # user is the author of the question
    when @question.find_author.id
      case @question.status
      when Question.open
        @question.update(status: Question.author_approved)
      when Question.instructor_approved
        @question.update(status: Question.both_approved)
      else
      end
    # User is the instructor
    when @question.topic.find_root.find_instructor
      case @question.status
      when Question.open
        @question.update(status: Question.instructoror_approved)
      when Question.author_approved
        @question.update(status: Question.both_approved)
      else
      end
    # User is someone else
    else
      @question.update(rank: :rank+1)
    end
    redirect_to @question
  end

  def rank_down
    case current_user.id
    # User is the instructor
    when @question.topic.find_root.find_instructor
      case @question.status
      when Question.open
        @question.update(status: Question.instructoror_approved)
      when Question.author_approved
        @question.update(status: Question.both_approved)
      else
      end
    # User is someone else
    else
      @question.update(rank: :rank - 1)
    end
    render @question
  end

  private
  def set_question
    @question = Question.find(params[:id])
  end

  def question_params
    params.require(:question).permit(:title, :description)
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_question.html.erb
<div class="panel panel-default">
  <!-- Default panel contents -->
  <div class="panel-heading"><b><%= question.title %></b></div>
  <div class="panel-body" style="background-color:#b9b7b7">
    <div class="container">
      <div class="row">
        <div class="col-md-10"><%= question.description %></div>
        <div class="col-md-1" align="right"><%= question.rank %></div>
        <div class="col-md-1" align="right">
          <button type="button" class="btn btn-primary" ><span class="glyphicon glyphicon-chevron-up" aria-hidden="true"></span></button> 
          <button type="button" class="btn btn-primary"><span class="glyphicon glyphicon-chevron-down" aria-hidden="true"></span></button> 
        </div>  
      </div>
    </div>
  </div>

  <!-- List group -->
  <ul class="list-group">
    <% if not question.answers.nil? %>
      <%= render question.answers %>
    <% else %>
      <li class="list-group-item">Não há respostas ainda</li>
    <% end %>
    <% @question = question %>
    <%= render 'answers/new', :question_id => @question.id%>
  </ul>
</div>

app/views/questions/create.html.erb
<h1>Questions#create</h1>
<p>Find me in app/views/questions/create.html.erb</p>

app/views/questions/destroy.html.erb
<h1>Questions#destroy</h1>
<p>Find me in app/views/questions/destroy.html.erb</p>

app/views/questions/edit.html.erb
<h1>Questions#edit</h1>
<p>Find me in app/views/questions/edit.html.erb</p>

app/views/questions/index.html.erb
<h1>Questions#index</h1>
<p>Find me in app/views/questions/index.html.erb</p>

app/views/questions/new.html.erb
<h1>Nova Pergunta</h1>

<%= form_for @question, url: questions_path, html: {class: "form-horizontal"} do |form| %>
  <div class="form-group">
    <%= form.label(:title, "Título", class: "col-sm-2 control-label")%>
    <div class="col-sm-4">
      <%= form.text_field(:title, class: "form-control") %>
    </div>
    <div class="col-sm-6">
    </div>
  </div>

  <div class="form-group">
    <%= form.label(:description, "Detalhes", class: "col-sm-2 control-label")%>
    <div class="col-sm-4">
      <%= form.text_area(:description, class: "form-control") %>
    </div>
    <div class="col-sm-6">
    </div>
  </div>
  
  <div class="col-sm-2">
    <button type="submit"class="btn btn-default">Enviar</button>
  </div>

<% end %>

app/views/questions/update.html.erb
<h1>Questions#update</h1>
<p>Find me in app/views/questions/update.html.erb</p>