config/routes.rb
Rails.application.routes.draw do
  
  get 'users/show'

  devise_for :users
  
  resources :classrooms,  
            :events,  
            :subscriptions,  
            :questions,  
            :topics,  
            :answers,
            :notifications
  
  get '/users/:id/show', to: 'users#show', as: 'user'
  
  get '/classroom/apply', to: 'classrooms#new_registration'
  
  post '/classroom/register', to: 'classrooms#register', as: 'registry'
  
  get '/users/:id/show', to: 'users#show', as: 'user_path'
  post '/questions/new'
  post '/answers/new'
  
  root 'welcome#index'

  get 'questions/rank_up'
  post 'questions/rank_up'
  get 'questions/rank_down'
  post 'questions/rank_down'
  post 'questions/_show'

end

app/models/classroom.rb
class Classroom < ActiveRecord::Base
  has_many :registrations
  has_many :topics
  has_many :events
  has_many :notifications

  validates :name, presence: true

  def self.student
    1
  end

  def self.instructor
    2
  end

  def find_instructor
    return self.registrations.find_by(status: Classroom.instructor).user
  end
end

app/controllers/classrooms_controller.rb
class ClassroomsController < ApplicationController
  before_action :set_classroom, only: [:show, :edit, :update, :destroy]
  
  before_action :authenticate_user!, only: [:new_registration, :new, :create, :edit, :update, :destroy]
  
  before_action :regs_params, only: [:register]
  
  def index
    @classrooms = Array.new
    @instructors = Array.new
    current_user.registrations.each do |registration|
      @classrooms.push(registration.classroom)
      @instructors.push(registration.classroom.find_instructor)
    end
  end

  def new
    @classroom = Classroom.new
  end

  def create
    @classroom = Classroom.new(classroom_params)
    
    respond_to do |format|
      if @classroom.save
        Registration.create(user_id:current_user.id, classroom_id:@classroom.id, status:Classroom.instructor)
        format.html {redirect_to @classroom, notice: "Aula criada com sucesso."}
      else
        format.html {render 'new'}
      end
    end
  end

  def edit
    @instructor = @classroom.find_instructor
    if current_user.id != @instructor.id
      redirect_to @classroom
    end
  end

  def update
    respond_to do |format|
      if @classroom.update(classroom_params)
        format.html {redirect_to @classroom, notice: "Aula atualizada com sucesso."}
      else
        format.html {redirect_to :edit}
      end
    end
  end

  def destroy
    @classroom.destroy

    respond_to do |format|
      format.html { redirect_to classrooms_url, notice: "Classroom successfully destroyed."}
    end
  end

  def show
    @instructor = @classroom.find_instructor
    @topics = @classroom.topics
  end

  def new_registration
    @registration = Registration.new
  end
  
  def register
    instructor = User.where(@us).first
    croom = Classroom.where(@cls).first
    
    
    respond_to do |format|
      
      if croom.nil?
        format.html {redirect_to classrooms_url, notice: "Código de aula inválido"}
      elsif instructor.nil?
        format.html {redirect_to classrooms_url, notice: "Email de professor inválido"}
      elsif !(croom.find_instructor == instructor)
        format.html {redirect_to classrooms_url, notice: "Combinação de Email e Código inválido"}
      elsif (instructor == current_user)
        format.html {redirect_to classrooms_url, notice: "Você não pode se inscrever como aluno em uma aula sua!"}
      elsif !(Registration.where(user:current_user, classroom:croom).first.nil?)
        format.html {redirect_to classrooms_url, notice: "Você já se inscreveu nesta aula!"}
      else
      Registration.create(user:current_user, classroom:croom, status:Classroom.student)
      format.html {redirect_to classrooms_url, notice: "Inscrição feita com sucesso!"}  
      end
    end
  end

  private
  def set_classroom
    @classroom = Classroom.find(params[:id])
  end

  def classroom_params
    params.require(:classroom).permit(:name, :description, :verification_code, :beginning, :end)
  end
  
  def regs_params
      @cls = params.require(:classroom).permit(:verification_code)
      @us = params.require(:user).permit(:email)
  end
end

app/helpers/classrooms_helper.rb
module ClassroomsHelper
end

app/views/classrooms/_header.html.erb
<!--
<div class="container-fluid">
<ul class="nav nav-tabs">
	<li role="presentation" class="active" style="width: 50%"><a href="#">Aulas</a></li>
  	<li role="presentation" style="width: 50%"><a href="/questions">Dúvidas</a></li>
</ul>
</br>
</div> -->

<div class="container-fluid" style="align: center">
		<h2>Minhas Aulas</h2>
</div>

app/views/classrooms/create.html.erb
<h1>Classrooms#create</h1>
<p>Find me in app/views/classrooms/create.html.erb</p>

app/views/classrooms/destroy.html.erb
<h1>Classrooms#destroy</h1>
<p>Find me in app/views/classrooms/destroy.html.erb</p>

app/views/classrooms/edit.html.erb
<h1>Editar Aula</h1>

<%= form_for @classroom, html: {class: "form-horizontal"} do |form| %>
  <div class="form-group">
    <%= form.label(:name, "Nome", class: "col-sm-2 control-label")%>
    <div class="col-sm-4">
      <%= form.text_field(:name, class: "form-control") %>
    </div>
    <div class="col-sm-6">
    </div>
  </div>

  <div class="form-group">
    <%= form.label(:description, "Descrição", class: "col-sm-2 control-label")%>
    <div class="col-sm-4">
      <%= form.text_field(:description, class: "form-control") %>
    </div>
    <div class="col-sm-6">
    </div>
  </div>
  
  <div class="form-group">
    <%= form.label(:verification_code, "Código de verificação", class: "col-sm-2 control-label")%>
    <div class="col-sm-4">
      <%= form.text_field(:verification_code, class: "form-control") %>
    </div>
    <div class="col-sm-6">
    </div>
  </div>

  <div class="form-group">
    <%= form.label(:beginning, "Data de início", class: "col-sm-2 control-label")%>
    <div class="col-sm-4">
      <%= form.date_select(:beginning, class: "form-control") %>
    </div>
    <div class="col-sm-6">
    </div>
  </div>

  <div class="form-group">
    <%= form.label(:end, "Data de término", class: "col-sm-2 control-label")%>
    <div class="col-sm-4">
      <%= form.date_select(:end, class: "form-control") %>
    </div>
    <div class="col-sm-6">
    </div>
  </div>

  <div class="col-sm-2">
    <button type="submit"class="btn btn-default">Salvar alterações</button>
  </div>

<% end %>

app/views/classrooms/index.html.erb
<%= render 'header'%>
<ol class="breadcrumb">
  <li><a href="/">Home</a></li>
  <li class="active">Classes</li>
</ol>
<div class="list-group">
  <% @classrooms.zip(@instructors).each do |classroom,instructor| %>
    <a href= "/classrooms/<%=classroom.id%>" class="list-group-item"><div><b><%= classroom.name %></b></div><div><%=instructor.name + " " + instructor.surname %></div></a>
  <% end %>
</div>
<div class="row">
	<div class="col-sm-6">
		<a class="btn btn-primary" href="/classroom/apply">Ingressar em aula <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span></a>
   
		<a class="btn btn-success" href="/classrooms/new">Ministrar nova aula <span class="glyphicon glyphicon-plus-sign" aria-hidden="true" align="right"></span></a>
	</div>
</div>

app/views/classrooms/new.html.erb
<div class="container-fluid">
<div class="row">
	<div class="col-sm-2 col-sm-offset-2">
		<h1>Nova aula</h1>
	</div>
</div>
</br>

<%= form_for @classroom, url: classrooms_path, html: {class: "form-horizontal"} do |form| %>
  <div class="form-group">
    <%= form.label(:name, "Nome", class: "col-sm-2 control-label")%>
    <div class="col-sm-4">
      <%= form.text_field(:name, class: "form-control") %>
    </div>
    <div class="col-sm-6">
    </div>
  </div>

  <div class="form-group">
    <%= form.label(:description, "Descrição", class: "col-sm-2 control-label")%>
    <div class="col-sm-4">
      <%= form.text_field(:description, class: "form-control") %>
    </div>
    <div class="col-sm-6">
    </div>
  </div>
  
  <div class="form-group">
    <%= form.label(:verification_code, "Código de verificação", class: "col-sm-2 control-label")%>
    <div class="col-sm-4">
      <%= form.text_field(:verification_code, class: "form-control") %>
    </div>
    <div class="col-sm-6">
    </div>
  </div>

  <div class="form-group">
    <%= form.label(:beginning, "Data de início", class: "col-sm-2 control-label")%>
    <div class="col-sm-4">
      <%= form.date_select(:beginning, class: "form-control") %>
    </div>
    <div class="col-sm-6">
    </div>
  </div>

  <div class="form-group">
    <%= form.label(:end, "Data de término", class: "col-sm-2 control-label")%>
    <div class="col-sm-4">
      <%= form.date_select(:end, class: "form-control") %>
    </div>
    <div class="col-sm-6">
    </div>
  </div>

	
	<div class="col-sm-2" align="right">
		<%= button_to "Voltar", :back, class:"btn btn-default" %>
	</div>


  <div class="col-sm-2">
    <%= form.submit "Criar", class:"btn btn-default" %>
  </div>

<% end %>

app/views/classrooms/new_registration.html.erb
<div class="container-fluid">
<div class="row">
	<div class="col-sm-2 col-sm-offset-2">
		<h1>Ingressar</h1>
	</div>
</div>
</br>

<%= form_for(@registration, url: registry_path(@registration), html: { class: "form-horizontal" }) do |f| %>

	<%= fields_for :classroom, @registration.classroom do |cs|%>
		
		  <div class="form-group">
		  	<%= cs.label(:verification_code, "Código", class: "col-sm-2 control-label") %>
		    <div class="col-sm-4">
		    <%= cs.text_field(:verification_code, class: "form-control") %>
		    </div>
		    <div class="col-sm-6">
		    </div>
		  </div>
	
	<%end%>
		  
	<%= fields_for :user do |ins|%>
	
		  <div class="form-group">
		  	<%= ins.label(:email, "Email do Professor", class: "col-sm-2 control-label") %>
		    <div class="col-sm-4">
		    <%= ins.email_field(:email, class: "form-control") %>
		    </div>
		    <div class="col-sm-6">
		    </div>
		  </div>
		  
	<%end %>
	

    <div class="col-sm-2 col-sm-offset-2" align="left">
    	<%= f.submit "Ingressar", class: "btn btn-default"%>
    </div>
  </div>
  
<%end%>

app/views/classrooms/show.html.erb
<div class="jumbotron">
  <h1><%= @classroom.name %></h1>
  <h2>Professor: <%= @instructor.name + " " + @instructor.surname %></h2>
  <%=@classroom.description %></br>
  <% if current_user.id == @instructor.id %>
    <%= link_to "Editar", :action => 'edit', :html => {class: "btn btn-primary"} %>
    <%= link_to "Novo tópico", :controller => 'topics', :action => 'new', :classroom_id => @classroom.id, :html => {class: "btn btn-primary"} %>
  <% end %>
</div>
<div class="list-group">
  <%= render @topics %>
</div>

app/views/classrooms/update.html.erb
<h1>Classrooms#update</h1>
<p>Find me in app/views/classrooms/update.html.erb</p>