config/routes.rb
Rails.application.routes.draw do
  
  get 'users/show'

  devise_for :users
  
  resources :classrooms,  
            :events,  
            :subscriptions,  
            :questions,  
            :topics,  
            :answers,
            :notifications
  
  get '/users/:id/show', to: 'users#show', as: 'user'
  
  get '/classroom/apply', to: 'classrooms#new_registration'
  
  post '/classroom/register', to: 'classrooms#register', as: 'registry'
  
  get '/users/:id/show', to: 'users#show', as: 'user_path'
  post '/questions/new'
  post '/answers/new'
  
  root 'welcome#index'

  get 'questions/rank_up'
  post 'questions/rank_up'
  get 'questions/rank_down'
  post 'questions/rank_down'
  post 'questions/_show'

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  validates :description, :question_id, presence: true

  belongs_to :question

  def self.normal
    0
  end

  def self.owner_approved
    1
  end

  def self.instructor_approved
    2
  end

  def self.instructor_flagged
    3
  end


end

app/models/classroom.rb
class Classroom < ActiveRecord::Base
  has_many :registrations
  has_many :topics
  has_many :events
  has_many :notifications

  validates :name, presence: true

  def self.student
    1
  end

  def self.instructor
    2
  end

  def find_instructor
    return self.registrations.find_by(status: Classroom.instructor).user
  end
end

app/models/event.rb
class Event < ActiveRecord::Base
  validates :name, :beginning, :end, presence: true
  belongs_to :classroom
end

app/models/notification.rb
class Notification < ActiveRecord::Base
  validates :title, :send_time, presence: true
  belongs_to :classroom
end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :topic
  has_many :answers
  has_many :subscriptions

  def self.open
    0
  end

  def self.author_approved
    1
  end

  def self.instructor_approved
    2
  end

  def self.both_approved
    3
  end

  def self.instructor_flagged
    4
  end

  def find_author
    return self.subscriptions.find_by(status: Subscription.author).user 
  end
end

app/models/registration.rb
class Registration < ActiveRecord::Base
  belongs_to :user
  belongs_to :classroom
  validates :status, presence: true
end

app/models/subscription.rb
class Subscription < ActiveRecord::Base
  belongs_to :user
  belongs_to :question

  def find_author
    return self.where(status: Subscription.author).user
  end
  
  def self.unfollow
    0
  end

  def self.author
    1
  end

  def self.follower
    2
  end
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  belongs_to :parent_topic, :class_name => "Topic", :foreign_key => "parent_topic_id"
  belongs_to :classroom

  has_many :child_topics, :class_name => "Topic", :foreign_key => "parent_topic_id"
  has_many :questions

  def find_root
    if :classroom_id.nil?
      return Topic.find(parent_topic_id).find_root
    else
      return :classroom_id
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :registrations
  has_many :subscriptions
  validates :name, :surname, presence: true
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :set_answer, only: [:show, :edit, :update, :destroy]
  
  def index
  end

  def new
    @answer = Answer.new
  end

  def create
    respond_to do |format|
      @answer = Answer.new(answer_params)
      if @answer.save
        @answer.update(rank: 0, status:Answer.normal)
        format.html { redirect_to @answer.question.topic }
      else
        format.html { redirect_to @answer.question.topic, notice: "Resposta não foi criada" }
      end
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @answer.update(answer_params)
        format.html { redirect_to @answer.question, notice: "Resposta atualizada com sucesso."}
      else
        format.html { redirect_to :edit}
      end
    end
  end

  def destroy
  end

  def show
  end

  private
  def set_answer
    @answer = Answer.find(params[:id])
  end

  def answer_params
    params.require(:answer).permit(:description, :question_id)
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end

  def show
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :set_topic, only: [:show, :edit, :update, :destroy]
  
  def index
    classroom_id = params[:classroom_id]
    parent_topic_id = params[:parent_topic_id]

    unless classroom_id.nil?
      @topics = Topic.where(classroom_id: classroom_id)
    else
      @topics = Topic.where(parent_topic_id: parent_topic_id)
    end
  end

  def new
    @topic = Topic.new
  end

  def create
    @topic = Topic.new(topic_params)
    classroom_id = params[:topic][:classroom_id]
    parent_topic_id = params[:parent_topic_id]

    respond_to do |format|
      if @topic.save
        # If the new topic is in the root of the classroom
        unless classroom_id.nil?
          @topic.update(classroom_id: classroom_id, parent_topic_id: nil)
        else # The new topic is under another topic
          @topic.update(classroom_id: nil, parent_topic_id: parent_topic_id)
        end
        format.html { redirect_to @topic, notice: "Tópico criado com sucesso." }
      else
        format.html { render 'new'}
      end
    end
  end

  def edit
    classroom_id = @topic.find_root
    @instructor = Classroom.find(classroom_id).find_instructor
    
    if current_user.id != @instructor.id
      redirect_to @topic
    end
  end

  def update
    respond_to do |format|
      if @topic.update(topic_params)
        format.html { redirect_to @topic, notice: "Tópico atualizado com sucesso."}
      else
        format.html { redirect_to :edit}
      end
    end
  end

  def destroy
    @topic.destroy

    respond_to do |format|
      format.html { redirect_to topics_url, notice: "Tópico excluído com sucesso."}
    end
  end

  def show
    @questions = @topic.questions
    @topics = Topic.where(parent_topic_id: @topic.id)
    flash[:topic_id] = @topic.id
    @answer = Answer.new
  end

  private
  def set_topic
    @topic = Topic.find(params[:id])
  end

  def topic_params
    params.require(:topic).permit(:title, :description)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user
  
  def show
  end
  
  def set_user
      @user = User.find(params[:id])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  
  before_action :authenticate_user!
  
  def index
    @registrations = current_user.registrations.where(status:1)
  end
end
  

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/classrooms_helper.rb
module ClassroomsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/answers/_answer.html.erb
<li class="list-group-item">
  <div class="container">
    <div class="row">
      <div class="col-md-10"><%= answer.description %></div>
      <div class="col-md-1" align="right"><%= answer.rank %></div>
      <div class="col-md-1" align="right">
        <button type="button" class="btn btn-default" ><span class="glyphicon glyphicon-chevron-up" aria-hidden="true"></span></button> 
        <button type="button" class="btn btn-default"><span class="glyphicon glyphicon-chevron-down" aria-hidden="true"></span></button> 
      </div>
    </div>
  </div>
</li>

app/views/answers/_form.html.erb
<%= form_for @answer do |form| %>
  <%= form.label :description %>
  <%= form.text_area :description, :placeholder => 'Sua resposta...' %>
  <%= form.submit %>
<% end %>

app/views/answers/_new.html.erb
<div>
  <%= form_for @answer, url: answers_path(@answer), html:{class: 'form-inline'} do |form| %>
    <div class="form-group">
      <div class="input-group">
        <%= form.text_area :description, class: "col-sm-10 form-control", placeholder: "Sua Resposta" %>
      </div>
        <%= form.hidden_field :question_id, value: @question.id %>
    <button type="submit" class="btn btn-default">Enviar</button>
  <% end %>
</div>

app/views/answers/create.html.erb
<h1>Answers#create</h1>
<p>Find me in app/views/answers/create.html.erb</p>

app/views/answers/destroy.html.erb
<h1>Answers#destroy</h1>
<p>Find me in app/views/answers/destroy.html.erb</p>

app/views/answers/edit.html.erb
<h1>Answers#edit</h1>
<p>Find me in app/views/answers/edit.html.erb</p>

app/views/answers/index.html.erb
<h1>Answers#index</h1>
<p>Find me in app/views/answers/index.html.erb</p>

app/views/answers/new.html.erb
<h1>Answers#new</h1>
<p>Find me in app/views/answers/new.html.erb</p>

app/views/answers/show.html.erb
<h1>Answers#show</h1>
<p>Find me in app/views/answers/show.html.erb</p>

app/views/answers/update.html.erb
<h1>Answers#update</h1>
<p>Find me in app/views/answers/update.html.erb</p>

app/views/events/create.html.erb
<h1>Events#create</h1>
<p>Find me in app/views/events/create.html.erb</p>

app/views/events/destroy.html.erb
<h1>Events#destroy</h1>
<p>Find me in app/views/events/destroy.html.erb</p>

app/views/events/edit.html.erb
<h1>Events#edit</h1>
<p>Find me in app/views/events/edit.html.erb</p>

app/views/events/index.html.erb
<h1>Events#index</h1>
<p>Find me in app/views/events/index.html.erb</p>

app/views/events/new.html.erb
<h1>Events#new</h1>
<p>Find me in app/views/events/new.html.erb</p>

app/views/events/show.html.erb
<h1>Events#show</h1>
<p>Find me in app/views/events/show.html.erb</p>

app/views/events/update.html.erb
<h1>Events#update</h1>
<p>Find me in app/views/events/update.html.erb</p>

app/views/topics/_index.html.erb
<div class="list-group">
  <% @topics.each do |topic| %>
    <a href= "/topics/<%=topic.id%>" class="list-group-item"><div><b><%= topic.title %></b></div><div><%=topic.description %></div></a>
  <% end %>
</div>

app/views/topics/_topic.html.erb
<a href= "/topics/<%=topic.id%>" class="list-group-item"><div><b><%= topic.title %></b></div><div><%=topic.description %></div></a>

app/views/topics/create.html.erb
<h1>Topics#create</h1>
<p>Find me in app/views/topics/create.html.erb</p>

app/views/topics/destroy.html.erb
<h1>Topics#destroy</h1>
<p>Find me in app/views/topics/destroy.html.erb</p>

app/views/topics/edit.html.erb
<h1>Topics#edit</h1>
<p>Find me in app/views/topics/edit.html.erb</p>

app/views/topics/index.html.erb
<h1>Topics#index</h1>
<p>Find me in app/views/topics/index.html.erb</p>

app/views/topics/new.html.erb
<h1>Novo Tópico</h1>

<%= form_for @topic, url: topics_path, html: {class: "form-horizontal"} do |form| %>
  <div class="form-group">
    <%= form.label(:title, "Nome", class: "col-sm-2 control-label")%>
    <div class="col-sm-4">
      <%= form.text_field(:title, class: "form-control") %>
    </div>
    <div class="col-sm-6">
    </div>
  </div>

  <div class="form-group">
    <%= form.label(:description, "Descrição", class: "col-sm-2 control-label")%>
    <div class="col-sm-4">
      <%= form.text_field(:description, class: "form-control") %>
    </div>
    <div class="col-sm-6">
    </div>
  </div>
  
  <%= form.hidden_field :classroom_id, value: params[:classroom_id]%>
  <div class="col-sm-2">
    <button type="submit"class="btn btn-default">Criar</button>
  </div>

<% end %>

app/views/topics/show.html.erb
<h2>Tópicos</h2>
<div class="list-group">
  <%= render @topics %>
</div>

<h2>Dúvidas</h2>
<div>
  <p>
    <%= button_to "Nova Pergunta", new_question_path, class: "btn btn-primary" %>
  </p>  
</div>

<div class="list-group">
  <% if not @questions.nil? %>
    <%= render @questions, :questions => @questions %>
  <% end %>
</div>

app/views/topics/update.html.erb
<h1>Topics#update</h1>
<p>Find me in app/views/topics/update.html.erb</p>

app/views/users/show.html.erb
<div class="container">
<h1> <%= !@user.nickname.nil? ? @user.nickname : (@user.name + " " + @user.surname) %></h1>
</br>
<dl class="dl-horizontal">
  <dt>Nome</dt>
  <dd><%= @user.name%></dd>
  </br>
  <dt>Sobrenome</dt>
  <dd><%= @user.surname%></dd>
  </br>
  <dt>Apelido</dt>
  <dd><%= @user.nickname.nil? ? "Shii, não tem apelido..." : @user.nickname%></dd>
  </br>
  <dt>E-mail</dt>
  <dd><%= @user.email%></dd>
</dl>


</div>